language: node_js
node_js:
  - "iojs"
  - "8.11.3"
before_install:
  - npm install
  - npm install -g webpack
  - npm install -g webpack-cli
  - npm run build_only
cache:
  directories:
    - "node_modules"